declare const styles: {
  readonly "select2-close-mask": string;
  readonly "select2-container": string;
  readonly "select2-container--above": string;
  readonly "select2-container--below": string;
  readonly "select2-container--classic": string;
  readonly "select2-container--default": string;
  readonly "select2-container--disabled": string;
  readonly "select2-container--focus": string;
  readonly "select2-container--open": string;
  readonly "select2-dropdown": string;
  readonly "select2-dropdown--above": string;
  readonly "select2-dropdown--below": string;
  readonly "select2-hidden-accessible": string;
  readonly "select2-results": string;
  readonly "select2-results__group": string;
  readonly "select2-results__option": string;
  readonly "select2-results__option--highlighted": string;
  readonly "select2-results__options": string;
  readonly "select2-search--dropdown": string;
  readonly "select2-search--hide": string;
  readonly "select2-search--inline": string;
  readonly "select2-search__field": string;
  readonly "select2-selection--multiple": string;
  readonly "select2-selection--single": string;
  readonly "select2-selection__arrow": string;
  readonly "select2-selection__choice": string;
  readonly "select2-selection__choice__remove": string;
  readonly "select2-selection__clear": string;
  readonly "select2-selection__placeholder": string;
  readonly "select2-selection__rendered": string;
};
export = styles;

