declare const styles: {
  readonly "smfpIcon": string;
  readonly "smfpIcon-admin": string;
  readonly "smfpIcon-dependence-industries": string;
  readonly "smfpIcon-details": string;
  readonly "smfpIcon-economical-analysis": string;
  readonly "smfpIcon-edit": string;
  readonly "smfpIcon-element": string;
  readonly "smfpIcon-element-stats": string;
  readonly "smfpIcon-environment": string;
  readonly "smfpIcon-environment-analysis": string;
  readonly "smfpIcon-export": string;
  readonly "smfpIcon-global-price": string;
  readonly "smfpIcon-illustrated-information": string;
  readonly "smfpIcon-import": string;
  readonly "smfpIcon-information-analysis": string;
  readonly "smfpIcon-iran": string;
  readonly "smfpIcon-legal-analysis": string;
  readonly "smfpIcon-mine": string;
  readonly "smfpIcon-mineral": string;
  readonly "smfpIcon-political-analysis": string;
  readonly "smfpIcon-register-form": string;
  readonly "smfpIcon-remove": string;
  readonly "smfpIcon-reset": string;
  readonly "smfpIcon-secondary-production": string;
  readonly "smfpIcon-secondary-sources": string;
  readonly "smfpIcon-social-analysis": string;
  readonly "smfpIcon-strategic-analysis": string;
  readonly "smfpIcon-technological-level": string;
  readonly "smfpIcon-technology-analysis": string;
  readonly "smfpIcon-threats": string;
  readonly "smfpIcon-total-stats": string;
  readonly "smfpIcon-upstream-industry": string;
  readonly "smfpIcon-user": string;
  readonly "smfpIcon-world": string;
};
export = styles;

